// Uris - All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace UIGameplayTags
{
// UI Widget Stack Containers
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_Modal);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameMenu);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameHud);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_FrontEnd);

// UI Widgets
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_PressAKey);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainMenu);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_ConfirmScreen);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_HostNewGame);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_JoinGame);
TOGETHER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_Options);
}
