;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig = True
WarnOnInvalidTags = True
ClearInvalidTags = False
AllowEditorTagUnloading = True
AllowGameTagUnloading = False
FastReplication = False
bDynamicReplication = False
InvalidTagCharacters = "\"\',"
NumBitsForContainerSize = 6
NetIndexFirstBitSegment = 16
+GameplayTagList = (Tag="UI.Icons",DevComment="UI Icon Set")
+GameplayTagList = (Tag="UI.Icons.Chevron.Left",DevComment="Chevron.Left")
+GameplayTagList = (Tag="UI.Icons.Chevron.Right",DevComment="Chevron.Right")
+GameplayTagList = (Tag="UI.Icons.Help",DevComment="Help")
+GameplayTagList = (Tag="UI.Icons.Info",DevComment="Info Icon")
+GameplayTagList = (Tag="UI.Image",DevComment="")
+GameplayTagList = (Tag="UI.Image.Test",DevComment="")
+GameplayTagList = (Tag="UI.Input",DevComment="")
+GameplayTagList = (Tag="UI.Input.Gamepad",DevComment="")
+GameplayTagList = (Tag="UI.Input.Gamepad.PS",DevComment="")
+GameplayTagList = (Tag="UI.Input.Gamepad.PS.FaceDown",DevComment="")
+GameplayTagList = (Tag="UI.Input.Gamepad.PS.FaceLeft",DevComment="")
+GameplayTagList = (Tag="UI.Input.Gamepad.PS.FaceRight",DevComment="")
+GameplayTagList = (Tag="UI.Input.Gamepad.PS.FaceUp",DevComment="")
+GameplayTagList = (Tag="UI.Input.Keyboard",DevComment="")
+GameplayTagList = (Tag="UI.Input.Keyboard.Del",DevComment="")
+GameplayTagList = (Tag="UI.Input.Keyboard.Esc",DevComment="")
+GameplayTagList = (Tag="UI.Input.Mouse",DevComment="")
+GameplayTagList = (Tag="UI.SoundFX",DevComment="Sound Effects for UI")
+GameplayTagList = (Tag="UI.SoundFX.Button.Hover",DevComment="")
+GameplayTagList = (Tag="UI.SoundFX.Button.Select",DevComment="")
+GameplayTagList = (Tag="UI.SoundFX.List.Hover",DevComment="")
+GameplayTagList = (Tag="UI.SoundFX.List.Select",DevComment="")
+GameplayTagList = (Tag="UI.SoundFX.State",DevComment="")
+GameplayTagList = (Tag="UI.SoundFX.State.Error",DevComment="")

